In [1]:
l=[1,2,3,4,5,6,7,8,9,10]

In [2]:
sum=0
product=1
for i in l:
    sum= sum+i
    product=product*i
print(sum,product)

55 3628800

In [1]:
sum=0
product=1
a=0
n=10
while a<n:
    a=a+1
    sum = sum+a
    product=product*a
print(sum,product)

55 3628800

In [2]:
units= int(input("enter the units consumed"))

if units<=100:
    payment= 4.5*units
    print(payment)
elif units<=200:
    p=int(input("enter the unit again"))
    payment= 4.5*100+6*(200)-6*(300-p)
    print(payment)
elif units<=300:
    q=int(input("enter the unit again"))
    payment=4.5*100+6*100+10*300-10*(500-q)
    print(payment)
else:
    r=int(input("enter the unit again"))
    payment=4.5*100+6*100+10*100+20*(r-300)
    print(payment)

enter the units consumed 310
enter the unit again 310

2250.0

In [31]:
l=list(range(1,101))
for x in l:
    a=x*x*x
    print(a)
for i in range(1,1000000) :
    if(i%4==0 or i%5==0):
        
        divisible_by_4or5.append(i)

1
8
27
64
125
216
343
512
729
1000
1331
1728
2197
2744
3375
4096
4913
5832
6859
8000
9261
10648
12167
13824
15625
17576
19683
21952
24389
27000
29791
32768
35937
39304
42875
46656
50653
54872
59319
64000
68921
74088
79507
85184
91125
97336
103823
110592
117649
125000
132651
140608
148877
157464
166375
175616
185193
195112
205379
216000
226981
238328
250047
262144
274625
287496
300763
314432
328509
343000
357911
373248
389017
405224
421875
438976
456533
474552
493039
512000
531441
551368
571787
592704
614125
636056
658503
681472
704969
729000
753571
778688
804357
830584
857375
884736
912673
941192
970299
1000000

In [2]:
l=list(range(1,101))
divisible_by_4or5=[]
for x in l:
    a=x*x*x
    print(a)
for i in range(1,1000000) :
    if(i%4==0 or i%5==0):
        
        divisible_by_4or5.append(i)

1
8
27
64
125
216
343
512
729
1000
1331
1728
2197
2744
3375
4096
4913
5832
6859
8000
9261
10648
12167
13824
15625
17576
19683
21952
24389
27000
29791
32768
35937
39304
42875
46656
50653
54872
59319
64000
68921
74088
79507
85184
91125
97336
103823
110592
117649
125000
132651
140608
148877
157464
166375
175616
185193
195112
205379
216000
226981
238328
250047
262144
274625
287496
300763
314432
328509
343000
357911
373248
389017
405224
421875
438976
456533
474552
493039
512000
531441
551368
571787
592704
614125
636056
658503
681472
704969
729000
753571
778688
804357
830584
857375
884736
912673
941192
970299
1000000

In [18]:
string=("I want to be a data scientist")
count=0
for x in string:
    if(x=="a",x=="e",x=="i",x=="o",x=="u",x=="A",x=="E",x=="I",x=="O",x=="U"):
        count+=1
        print (count)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29